### ISSUE TITLE
sync 出现问题 (

### ISSUE THREAD

**Issue by HiedaNaKan** [ManbangGroup/Phantom#12]
Caused by: groovy.lang.MissingMethodException: No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []
	at com.wlqq.phantom.gradle.host.PhantomHostPlugin$_apply_closure1.doCall(PhantomHostPlugin.groovy:44)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
	at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:155)
	at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:228)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:222)
	at com.android.build.gradle.AppExtension.addVariant(AppExtension.java:87)
	at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:132)
	at com.android.build.gradle.BasePlugin.lambda$createAndroidTasks$6(BasePlugin.java:789)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:775)
	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:670)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)

**Comment by MikaGuraNTK** [comment]
切换到了gradle 3.3 用了  classpath 'com.android.tools.build:gradle:2.3.3' 
提示 


* What went wrong:
A problem occurred evaluating project ':helloworld'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 4.1. Current version is 3.3.

可是你build.gradle用的就是2.3.3呀 (((

**Comment by Ccixyj** [comment]
希望能够尽快升级到agp 3.3

**Comment by shaobin0604** [comment]
Phantom v3.1.2 已兼容 Gradle 2.3.3 ~ 4.4 + AGP 2.3.3 ~ 3.1.4 ，请升级到该版本
