### ISSUE TITLE
gradle4.10.1  com.android.tools.build:gradle:3.3.1报错，这个麻烦解决一下，大神

### ISSUE THREAD

**Issue by ewgcat** [ManbangGroup/Phantom#16]
Caused by: groovy.lang.MissingMethodException: No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeAssetsTask() is applicable for argument types: () values: []
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:71)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.wlqq.phantom.gradle.host.PhantomHostPlugin$_apply_closure1.doCall(PhantomHostPlugin.groovy:50)

**Comment by ewgcat** [comment]
demo

**Comment by JoinKing** [comment]
把版本改成 classpath "com.android.tools.build:gradle:3.1.4"，就可以解决，我第一次集成也是这样

**Comment by ewgcat** [comment]
好的，谢谢


 
---原始邮件---
发件人: "Flutter_King"<notifications@github.com>
发送时间: 2019年4月28日(星期日) 下午4:01
收件人: "ManbangGroup/Phantom"<Phantom@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"ewgcat"<850716183@qq.com>;
主题: Re: [ManbangGroup/Phantom] gradle4.10.1  com.android.tools.build:gradle:3.3.1报错，这个麻烦解决一下，大神 (#16)



把版本改成 classpath "com.android.tools.build:gradle:3.1.4"，就可以解决，我第一次集成也是这样

**Comment by Ccixyj** [comment]
android.tools.build 可以支持依稀3.2.x吗

**Comment by ewgcat** [comment]
不可以




------------------
                   
              
                              李帅华  安卓开发工程师
         
广州易健科技有限公司
         
             电话：18986170640         
         
             邮箱： lishuaihua@ejoyst.com
         
             网址：https://www.ejoyst.com
         
             地址：广州市越秀区沿江中路296号江湾商业中心11楼

 
     
 


 




------------------ 原始邮件 ------------------
发件人: "Maxium_R"<notifications@github.com>;
发送时间: 2019年5月11日(星期六) 中午12:00
收件人: "ManbangGroup/Phantom"<Phantom@noreply.github.com>;
抄送: "JackLee"<850716183@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ManbangGroup/Phantom] gradle4.10.1  com.android.tools.build:gradle:3.3.1报错，这个麻烦解决一下，大神 (#16)




android.tools.build 可以支持依稀3.2.x吗

**Comment by e9ab98e991ab** [comment]
AndroidX支持吗？

**Comment by ewgcat** [comment]
不


------------------
                   
              
                              李帅华  安卓开发工程师
         
广州易健科技有限公司
         
             电话：18986170640         
         
             邮箱： lishuaihua@ejoyst.com
         
             网址：https://www.ejoyst.com
         
             地址：广州市越秀区沿江中路296号江湾商业中心11楼

 
     
 


 




------------------ 原始邮件 ------------------
发件人: "e9ab98e991ab"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 中午12:25
收件人: "ManbangGroup/Phantom"<Phantom@noreply.github.com>;
抄送: "JackLee"<850716183@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ManbangGroup/Phantom] gradle4.10.1  com.android.tools.build:gradle:3.3.1报错，这个麻烦解决一下，大神 (#16)




AndroidX支持吗？

**Comment by mallxiaodoudou** [comment]
同问 android.tools.build 可以支持支持一下3.2.x吗

**Comment by shenhcen0614** [comment]
可以支持3.4.2吗

**Comment by JoinKing** [comment]
我已经放弃了，我之前3.3.1都没有测试成功



viphwq@163.com
 
发件人： shenhcen0614
发送时间： 2019-10-25 10:17
收件人： ManbangGroup/Phantom
抄送： Flutter_King; Comment
主题： Re: [ManbangGroup/Phantom] gradle4.10.1 com.android.tools.build:gradle:3.3.1报错，这个麻烦解决一下，大神 (#16)
可以支持3.4.2吗
